# Generated by Django 4.1.1 on 2022-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0002_auto_20220701_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=200)),
                ('busfrom', models.CharField(max_length=200)),
                ('busto', models.CharField(max_length=200)),
                ('busdate', models.DateField(max_length=200)),
                ('bustime', models.TimeField(max_length=200)),
            ],
        ),
    ]
