# Generated by Django 4.1.1 on 2022-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0003_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='busimage',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images/'),
        ),
    ]
