# Generated by Django 4.1.1 on 2022-09-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0004_buses_busimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='busimage',
            field=models.ImageField(blank=True, null=True, upload_to='busimages/'),
        ),
    ]
