# Generated by Django 4.1.1 on 2022-09-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0006_buses_busnoofseats_buses_busremseats_buses_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='price',
            new_name='busprice',
        ),
    ]
