# Generated by Django 4.1.1 on 2022-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0007_rename_price_buses_busprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='busnumplate',
            field=models.CharField(default='UBA 123A', max_length=200),
        ),
    ]
