# Generated by Django 4.1.1 on 2022-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0008_buses_busnumplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('bus_station', models.CharField(max_length=200)),
            ],
        ),
    ]
