# Generated by Django 4.1.1 on 2022-09-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0009_bookbus'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookedseats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(default=0, max_length=200)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spongebob.buses')),
            ],
        ),
    ]
