# Generated by Django 4.0.6 on 2022-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0012_bus_busbooking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(default='UBA 123A', max_length=100),
        ),
    ]
