# Generated by Django 4.0.6 on 2022-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0013_bus_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
