# Generated by Django 4.0.6 on 2022-09-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0014_alter_bus_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseats',
            name='bus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spongebob.bus'),
        ),
    ]
