# Generated by Django 4.0.6 on 2022-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0015_alter_bookedseats_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='remaining_seats',
            field=models.IntegerField(),
        ),
    ]
