# Generated by Django 4.0.6 on 2022-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0016_alter_bus_no_of_seats_alter_bus_remaining_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='remaining_seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
