# Generated by Django 4.0.6 on 2022-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0018_alter_bus_no_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(default='salafy_4.png', upload_to='busimages'),
        ),
    ]
