# Generated by Django 4.0.6 on 2022-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0019_alter_bus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='remaining_seats',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=2),
        ),
    ]
