# Generated by Django 4.0.6 on 2022-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0020_alter_bus_remaining_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(default='PANDA BUS', max_length=100),
        ),
    ]
