# Generated by Django 4.0.6 on 2022-09-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0022_alter_bookedseats_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseats',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spongebob.bus'),
        ),
    ]
