# Generated by Django 4.0.6 on 2022-09-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0023_alter_bookedseats_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='pick_up_station',
            new_name='bus_station',
        ),
    ]
