# Generated by Django 4.0.6 on 2022-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0025_bus_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='user_id',
            new_name='bus_admin_id',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='bus_admin_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='image',
            field=models.CharField(default='/1.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='number_plate',
            field=models.CharField(default='UBA 123A', max_length=100),
        ),
    ]
