# Generated by Django 4.0.6 on 2022-10-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0026_rename_user_id_bus_bus_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
