# Generated by Django 4.0.6 on 2022-10-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0027_busbooking_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='image',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='number_plate',
        ),
    ]
