# Generated by Django 4.0.6 on 2022-10-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spongebob', '0030_alter_busbooking_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='number_plate',
            field=models.CharField(default='UBA 123A', max_length=30),
        ),
    ]
